### ISSUE TITLE
Install & Usage

### ISSUE THREAD

**Issue by bdysonwebb** [segovoni/sqlcmdcli#2]
Please forgive my ignorance, but I can't seem to get this to work.

I've extracted sqlcmdcli.exe to my D:\ drive, opened a CMD prompt and type sqlcmdcli.exe altercolumn -servername:WOBLCND8234ZTP -databasename:JDE_EP -username:admin -password:###### -schema:dbo -table:F0004 -column:DTSY -type:varchar(4) -verbose, but nothing happens.

what am I missing or doing wrong?

**Comment by segovoni** [comment]
Hi @bdysonwebb, 

thanks for using sqlcmdcli, I tried the released version in my test environment on AdventureWorks database and it worked properly. I used a command equal to the one you have used:

`sqlcmdcli.exe altercolumn -servername:sql2022 -databasename:AdventureWorks2019 -username:sgovoni -password:##### -schema:Person -table:Address -column:AddressLine1 -type:nvarchar(120) -verbose`

![image](https://user-images.githubusercontent.com/23333277/197344684-a2da81a8-8dab-4abc-9ff4-9c2b86243150.png)

What error did you get? If you have not received any errors, the connection attempt was probably in progress and would have timed out.

Did you run sqlcmdcli on the same server where the SQL Server instance is?

Does the windows user you used have execute rights on d:\ drive?

A print screen of the error would be helpful.

Thanks!

**Comment by segovoni** [comment]
Hi @bdysonwebb,

have you had the opportunity to try with the latest version of sqlcmdcli? Let me know if you need help in the meantime I will close the issue.

Another option to alter a column with dependencies is to use the sp_alter_column stored procedure that you can find [here](https://github.com/segovoni/sp_alter_column).

Bye
